# Generated by Django 2.1.1 on 2019-08-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0003_auto_20190812_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_enrollment',
            name='aadhar_no',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='voters_enrollment',
            name='aadhar_no',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
