# Generated by Django 2.1.1 on 2019-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0005_voters_enrollment_voter_aadhar_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_enrollment',
            name='candidate_aadhar_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
