# Generated by Django 2.1.1 on 2019-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0006_candidate_enrollment_candidate_aadhar_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_enrollment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voters_enrollment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
