# Generated by Django 2.1.1 on 2019-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0007_auto_20190812_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_enrollment',
            name='count_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voters_enrollment',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
