# Generated by Django 2.1.1 on 2019-08-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0008_auto_20190812_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_enrollment',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='voters_enrollment',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
