# Generated by Django 2.1.1 on 2019-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0010_auto_20190813_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_enrollment',
            name='party',
            field=models.CharField(default='', max_length=200),
        ),
    ]
