# Generated by Django 2.1.1 on 2019-08-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0011_candidate_enrollment_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_enrollment',
            name='tokens',
            field=models.CharField(default='', max_length=20),
        ),
    ]
