# Generated by Django 2.1.1 on 2019-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0012_voters_enrollment_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_enrollment',
            name='token_expire',
            field=models.BooleanField(default=False),
        ),
    ]
