# Generated by Django 2.1.1 on 2019-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0013_voters_enrollment_token_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_enrollment',
            name='mobile_no',
            field=models.IntegerField(default=''),
        ),
    ]
