# Generated by Django 2.1.1 on 2019-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0014_voters_enrollment_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters_enrollment',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
    ]
