# Generated by Django 2.1.1 on 2019-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0015_auto_20190815_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters_enrollment',
            name='mobile_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
