# Generated by Django 2.1.1 on 2019-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0016_auto_20190815_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters_enrollment',
            name='mobile_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
