# Generated by Django 2.1.1 on 2019-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0017_auto_20190815_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters_enrollment',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='voters_enrollment',
            name='mobile',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
