# Generated by Django 2.1.1 on 2019-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0018_auto_20190818_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters_enrollment',
            name='token_expire',
        ),
        migrations.AlterField(
            model_name='voters_enrollment',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='voters_enrollment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
