# Generated by Django 2.1.1 on 2019-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0020_remove_voters_enrollment_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_enrollment',
            name='token_expire',
            field=models.BooleanField(default=False),
        ),
    ]
