# Generated by Django 2.1.1 on 2019-08-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0021_voters_enrollment_token_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_enrollment',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
