# Generated by Django 2.1.1 on 2019-08-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0022_voters_enrollment_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters_enrollment',
            name='mobile',
        ),
    ]
