# Generated by Django 2.1.1 on 2019-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0023_remove_voters_enrollment_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes_Casted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
